language: java
jdk:
- oraclejdk8
services:
- postgresql
install:
- echo "Skip install step"
before_script:
- psql -c 'create database bikerental;' -U postgres
- cat .config/travis.application.properties > src/main/resources/application.properties
script:
- mvn clean package
- before_deploy:
  - cat .config/heroku.application.properties > src/main/resources/application.properties
  - echo "${DB_PASSWORD}" >> src/main/resources/application.properties
  - echo "${DB_URL}" >> src/main/resources/application.properties
  - echo "${DB_USERNAME}" >> src/main/resources/application.properties
  - echo "${TOKEN_SECRET}" >> src/main/resources/application.properties
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: heroku
  api_key:
    secure: EOznXEpyqss6+3H1d72pMujBCYYIG5ZjBq/6e7RgTpSfJvyQbu+OgUTJ/Kn5ZeO1uglJWCDOabyOW08Z8kG3TMrPoOYO43cMeDDgMR+PyhkaLQuXbVJjXDk0ymKsrptbb3z6I8uSNLBIkTLmyaOKtdnsSJiVK7X8y2V3cC44Kz8vuau3LlSxKgAqpvyFW4eTIRcUSeZ/Qe2PxOEwoZ9bUphYHUbKiA9wGOgy5Gi8u9YYAEGqNCM1JvGxSoS0NJ00Uh3alWeybZ9G460s+lC0LbxkPpGmAYSZMjcjda5OgoKJEcLbdPXQInSZRiDfmNZTK7bfHgCjx0R+GlnVByFuk22TJuS5B6ch1sGFGPEGYQDfoe/E98Aw0PPTvteA301TF8fzZKa+3pObArVTHp/vK3waODcocTgghqLvA4KPp0T/apysGqr5WSa4LgIwxrvKB/gk5b1rQiWddJIyF8AYbxEBarAeanR2nYmsb0avQYFFn1LO/RPgbQ+TB5t1qaK4EYUEojqhkb2Johe8RdnCuRAv+KJ7pbrmsO722/BT5OVB+PFF9ifAS4MTk4UUEluPvkWmZVcIPyGOnSafAE5zHXXIWAreUys1HiWLdcXExlWAj0D6RVnGg7rKXXINpR+L/fxYtjm/waLpQ+iKn6TDDi61NcGfRzOtcRErkYgXzEI=
  on:
    branch: master
cache:
  directories:
  - "$HOME/.m2"
notifications:
  email: false
