language: java

jdk:
  - oraclejdk8

services:
  - postgresql

install:
  - echo "Skip install step"

before_script:
  - psql -c 'create database bikeRental;' -U postgres
 # - cat .config/travis.application.properties > src/main/resources/application.properties

script:
  - mvn clean package

cache:
  directories:
  - $HOME/.m2

notifications:
  email: false
